name: Latest Medium Stories Workflow
on:
  # Run workflow automatically
  schedule:
    # # Runs every hour, on the hour
    # - cron: "0 * * * *"
    # Runs at midnight everyday
    - cron: "0 0 * * *"
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-STORY-LIST"
          commit_message: "Updated readme with the latest Medium posts"
          feed_list: "https://medium.com/feed/topic/data-science"
          max_post_count: "10"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDIUM-STORY-LIST-SONERY"
          commit_message: "Updated readme with the latest Medium posts from Sonery"
          feed_list: "https://sonery.medium.com/feed"
          max_post_count: "5"
